### ISSUE TITLE
newest s3 scripts guess the mime-type and have a recursive copy option

### ISSUE THREAD

**Issue by iambumblehead** [foo-software/s3-directory-sync-cli#11]
https://docs.aws.amazon.com/cli/latest/reference/s3/cp.html

I was able to do this earlier today before I found your package. Possibly the npm client scripts can do the same thing,
```bash
aws s3 cp ./build s3://mybucket/key --recursive
```

**Comment by adamhenson** [comment]
Hi @iambumblehead - is this issue a problem or a suggestion?

If it’s a problem - could you clearly describe what the expected result is, the actual result and provide a way to reproduce?

If it is a suggestion - could you clearly describe what you’re suggesting, why and the value it would provide?

**Comment by iambumblehead** [comment]
@adamhenson I'm sorry to create an incomplete ticket here feel free to close.

The purpose of my comment was to inform you that, essentially, if s3-directory-sync-cli used new aws client scripts there might be less "work" for this package to do, because it could use behavior provided by the aws client scripts. I believe recursive copying and mime-type creation weren't provided by aws-sdk scripts currently used by s3-directory-sync-cli.

**Comment by adamhenson** [comment]
Thanks @iambumblehead. I'm hesitant to introduce major changes to this project that don't change the functionality since it's not a project I'm actively trying to grow in any way. Thanks for the suggestion though.
