### ISSUE TITLE
thank you!

### ISSUE THREAD

**Issue by iambumblehead** [foo-software/s3-directory-sync-cli#8]
Hey I just wanted to let you know that this package works well for me. I'm using it in a ci job this way `npx @foo-software/s3-directory-sync-cli`

I'm looking for ways to invalidate the cloudfront cache but haven't found a package that works for that yet

**Comment by adamhenson** [comment]
You're welcome. I'd recommend using the AWS SDK for Node.js. Maybe you could write a script that calls [`cloudfront.createInvalidation`](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/CloudFront.html#createInvalidation-property).

**Comment by iambumblehead** [comment]
@adamhenson thanks I'm looking into and have found demonstrations of that call in other places
 * https://github.com/multiplegeorges/vue-cli-plugin-s3-deploy/blob/81b114a03404aee4cc5e5a244789deab172b15f8/src/deployer.js#L147-L183
 * https://docs.aws.amazon.com/cli/latest/reference/cloudfront/create-invalidation.html

**Comment by iambumblehead** [comment]
I haven't published this yet but it is working locally and s3-directory-sync is recommended in the README https://github.com/iambumblehead/s3-invalidate-cloudfront-id

**Comment by adamhenson** [comment]
Nice, thanks for the shout out.
