### ISSUE TITLE
files uploaded with s3-directory-sync-cli do not have the correct mime type

### ISSUE THREAD

**Issue by iambumblehead** [foo-software/s3-directory-sync-cli#9]
after uploading a web app then requesting the index.html file, the content type header sent with the file looks like this,
```
Content-Type: application/octet-stream
```

**Comment by iambumblehead** [comment]
this vue-cli tool which also uploads files sets a mimeType for each uploaded file https://github.com/multiplegeorges/vue-cli-plugin-s3-deploy/blob/master/src/bucket.js#L88

for an individual file, this example putObject call would set a mimeType
```javascript
s3.putObject({
  Bucket: bucketName,
  Key: key,
  ContentType: mime.lookup( file ),
  Body: buffer
})
```

**Comment by adamhenson** [comment]
Hi @iambumblehead - I think you're looking for the [`S3_DIRECTORY_SYNC_DERIVE_CONTENT_TYPE` parameter](https://github.com/foo-software/s3-directory-sync-cli#parameters). Just set that parameter to `true`.

We actually do the same as what you're suggesting in your comment:

https://github.com/foo-software/s3-directory-sync-cli/blob/d6c554b7f7a1673043a99cfa2c7c0bf83e94c66c/src/bin/sync.js#L134-L139

I'm closing this, but if your problem persists or if I'm misunderstanding - feel free to re-open.

**Comment by iambumblehead** [comment]
@adamhenson it looked to me like this value was set to 'true' by default. I'll try setting it explicitly and will let you know how it goes.

**Comment by adamhenson** [comment]
Ahhh yes, very good point @iambumblehead. Let me know how it goes. I think the documentation might be wrong in which case I'll open an issue.

**Comment by iambumblehead** [comment]
yes your script has this
```
  S3_DIRECTORY_SYNC_DERIVE_CONTENT_TYPE:
    process.env.S3_DIRECTORY_SYNC_DERIVE_CONTENT_TYPE === 'true',
```
but your readme shows that the default value is true

**Comment by adamhenson** [comment]
Yes, indeed... I'm also doing something a bit odd in which I support flags of the same name. I'm just doing some testing on my side to see if it impacts both ways of setting. But please do let me know if it works when you populate that value.

**Comment by adamhenson** [comment]
`S3_DIRECTORY_SYNC_PROGRESS` might have the same problem. I'm investigating.

**Comment by iambumblehead** [comment]
@adamhenson the mime-type is correct now. thank you for your quick replies.

**Comment by adamhenson** [comment]
Thanks again @iambumblehead. I updated docs and tests in #10.

This code is a bit outdated and should really use a package like [`meow`](https://www.npmjs.com/package/meow) to handle CLI flags... noted.

**Comment by iambumblehead** [comment]
@adamhenson it might be possible to use [aws-sdk/client-s3][0] ~4mb rather than [aws-sdk][1] ~70mb

I plan to try updating my cloudfront invalidation package to use [aws-sdk/client-cloudfront][3] and can let you know how that goes.

[0]: https://www.npmjs.com/package/@aws-sdk/client-s3
[1]: https://www.npmjs.com/package/aws-sdk
[3]: https://www.npmjs.com/package/@aws-sdk/client-cloudfront

**Comment by adamhenson** [comment]
Thanks!

**Comment by iambumblehead** [comment]
https://github.com/iambumblehead/s3-invalidate-cloudfront-id/pull/1

the interface for the newer client scripts is different but it works. The PR at the link above is working for me locally and I'm going to merge and publish it shortly.

this describes some of the changes/differences between the newer client scripts and older sdk ones
https://aws.amazon.com/jp/blogs/developer/modular-packages-in-aws-sdk-for-javascript/

also the 'login' is a little different with secret and access key nested inside a 'credentials' namespace

**Comment by iambumblehead** [comment]
also 'region' is required by the new client scripts
